quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=demo
quarkus.datasource.password=lala7

quarkus.datasource.jdbc.url=jdbc:postgresql://${pg.host:localhost:5432}/replicator
quarkus.datasource.jdbc.max-size=16
quarkus.datasource.jdbc.telemetry=true

quarkus.application.name=replicator
quarkus.otel.exporter.otlp.endpoint=http://${otel.host:localhost}:4317

quarkus.log.console.format=%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n


# The remote payment service we consult
quarkus.rest-client."de.bsd.replicator.PaymentService".url=http://${payment.hostport:localhost:8787}
%test.isTesting=true
%test.quarkus.rest-client."de.bsd.replicator.PaymentService".url=http://localhost:${quarkus.http.test-port}
quarkus.langchain4j.ollama.devservices.enabled=false
# AI related
quarkus.langchain4j.ollama.model1.base-url=http://localhost:11434
# No tool calling for codellama
# quarkus.langchain4j.ollama.model1.chat-model.model-name=codellama
# Granite supports tools
# quarkus.langchain4j.ollama.model1.chat-model.model-name=granite3.3:8b
quarkus.langchain4j.ollama.model1.chat-model.model-name=granite3.3:8b
quarkus.langchain4j.ollama.model1.timeout=60s
quarkus.langchain4j.ollama.model1.chat-model.temperature=0.2
quarkus.langchain4j.ollama.devservices.enabled=false

###
# Kafka related
kafka.bootstrap.servers=${kafka.host:localhost}:9092
mp.messaging.outgoing.topic1.connector=smallrye-kafka
mp.messaging.outgoing.topic1.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.outgoing.topic1.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
#
mp.messaging.incoming.topic2.connector=smallrye-kafka
mp.messaging.incoming.topic2.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.topic2.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
